assigner/__init__.py
#coding=utf-8

from flask import Blueprint
assigner=Blueprint('assigner',
        __name__,
        #template_folder='/opt/auras/templates/',   #指定模板路径
         #static_folder='/opt/auras/flask_bootstrap/static/',#指定静态文件路径
                   )

from . import views

assigner/views.py
#coding=utf-8
from flask import request, render_template, jsonify
from database.my_mysql import MysqlHandle
from my_time import *
from util.date_regex_handler import investDateHandler
from assigner import assigner
import re, json, yaml

mysql_settings=yaml.load(open('./yamls/mysql.yaml'))
mysql=MysqlHandle(mysql_settings)

country_map={
    'gn': 0,
    'gw': 1
}

industry_map={
    'other': u'其它',
    'xfsj': u'消费升级',
    'xjs': u'新技术',
    'qyfw': u'企业服务',
    'whyl': u'文娱+移动2C',
    'jr': u'互联网金融',
    'yl': u'医疗',
    'jy': u'教育',
    'dcx': u'大出行'
}
round_map={
    'zhongzi': u'种子轮',
    'tianshi': u'天使轮',
    'pre_a': u'Pre-A轮',
    'a': u'A轮',
    'a_add': u'A+轮',
    'pre_b': u'Pre-B轮',
    'b': u'B轮',
    'b_add': u'B+轮',
    'c': u'C轮',
    'd': u'D轮',
    'e': u'E轮',
    'f': u'F轮',
    'other': u'其它'
}

@assigner.route('/assign_industry', methods=['POST'])              #指定路由为/，因为run.py中指定了前缀，浏览器访问时，路径为http://IP/asset/
def assign_industry():
    industry_id = str(request.json['industry_id'])
    event_id = str(request.json['event_id'])
    updateSql = "UPDATE integrated_company SET industry = '"+industry_id+"' WHERE (id = " + event_id + ");"
    mysql.update(updateSql)
    return jsonify(
        code=0,
        msg= updateSql
    )


@assigner.route('/list', methods=('GET', 'POST'))              #指定路由为/，因为run.py中指定了前缀，浏览器访问时，路径为http://IP/asset/
def invest_list():
    print('__name__', __name__)
    return render_template('assigner/list.html')  #返回index.html模板，路径默认在templates下

@assigner.route('/invest_json', methods=('GET', 'POST'))
def invest_json():
    #orderBy =

    start = request.args.get('start') or 0
    industry = request.args.get('industry') or None
    _round = request.args.get('round') or None
    country = request.args.get('country') or None
    keyWords = request.args.get('keyWords') or None
    investDate = request.args.get('investDate') or None

    querySql='SELECT * FROM  integrated_company'
    countSql='SELECT COUNT(1) FROM  integrated_company'

    WHERE = ''
    if industry and industry in industry_map:
        WHERE += ' industry="%s"' % industry_map[industry]
    if _round and _round in round_map:
        if _round=='other':
            roundInfo = 'turn_level >= 16'
        else:
            roundInfo = ' finance_turn="%s"' % round_map[_round]
        if WHERE: WHERE += ' AND' + roundInfo
        else: WHERE += roundInfo

    if country and country in "gn|gw":
        if country=='gn':
            countryInfo=u' country="中国"'
        elif country=='gw':
            countryInfo=u' country!="中国"'

        if WHERE: WHERE += ' AND' + countryInfo
        else: WHERE += countryInfo

    if keyWords:
        keyInfo = ' (project_name LIKE "%'+ keyWords.strip() + '%" OR company_name like"%'+ keyWords.strip() +'%")'
        if WHERE: WHERE += ' AND' + keyInfo
        else: WHERE += keyInfo

    if investDate:
        dateLs=investDate.split('/')
        startDate=investDateHandler(dateLs[0])
        startTime=date2time(startDate)
        investInfo = ' finance_time >= %s' % startTime
        if len(dateLs)==2 and dateLs[1]:
            endDate=investDateHandler(dateLs[1])
            endTime=date2time(endDate)
            investInfo += ' AND finance_time <= %s' % endTime
        if WHERE: WHERE += ' AND' + investInfo
        else: WHERE += investInfo

    if WHERE:
        querySql += ' WHERE' + WHERE
        countSql += ' WHERE' + WHERE

    querySql += ' ORDER BY finance_time DESC LIMIT %s, 10' % start

    docs = mysql.query(querySql)
    count = mysql.query(countSql)

    print('__querySql:asddds ', querySql)
    resp={}

    resp['data']=docs
    resp['recordsTotal']=count[0]['COUNT(1)'] if count else 0
    resp['recordsLength']=count[0]['COUNT(1)'] if count else 0
    resp['recordsFiltered']=count[0]['COUNT(1)'] if count else 0
    return json.dumps(resp)

templates/assigner/list.html
<!DOCTYPE html>
<html>
    <head>
        <title>行业分类</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">

        <link rel='stylesheet' href='/static/stylesheets/style.css'/>
        <link rel="stylesheet" type="text/css" href="/static/stylesheets/jquery.dataTables.min.css">
        <style type="text/css" title="currentStyle">
         @import "/static/stylesheets/jquery-ui.css";
         @import "/static/stylesheets/jquery-base.css";
         td.details-control {
            background: url('/static/images/details_open.png') no-repeat center center;
            cursor: pointer;
         }
         tr.shown td.details-control {
            background: url('/static/images/details_close.png') no-repeat center center;
         }
        </style>
        <style>
        body{height:100%; overflow:hidden; margin:0px; padding:0px;}
        .box {height:100%; position:absolute; width:100%;}
        .center {text-align:center}
        .left {text-align:left}
        .auto_data {
               overflow: auto;
        }
        .auto {
               height: 88%;
               overflow: auto;
        }
        #invest tbody tr.selected {
          color: black;
          background-color: #faff9b;
          font-weight: bold;
        }
        #invest tbody tr.edited {
          color: #078e38;
        }
        .dataTables_length{
            margin: 0 23px;
        }
        .dataTables_filter{
            margin: 0 20px;
        }
        .head_filter{
            float: left;
            min-width: 50px;
            cursor: pointer;
            margin: 0 10px 5px 0;
            text-align: center;
            display: inline-block;
            padding: 2px 6px;
        }
        .filter_font{
            color:hotpink;
            font-weight: bold;
        }
        .row {
            width: 88%;
            max-width: 100%;
            min-width: 768px;
            margin: 0 auto;
            background-color: yellow;
        }
        .constrain{
            width: 88%;
            max-width: 100%;
            margin: 0 auto;
            padding: 0 20px;
        }
        .auto {
            height: 90%;
            overflow: auto;
        }
        .mytd {
            border-left: thin dashed grey;
            border-right: thin dashed grey;
            border-bottom: thin dashed grey;
            border-top: thin dashed grey;
        }
        </style>

        <script type="text/javascript" src="/static/javascripts/lib/datatable/jquery.js"></script>
        <script type="text/javascript" src="/static/javascripts/lib/datatable/jquery.dataTables.min.js"></script>

        <script>
          var assign_industry_url = "{{url_for('assigner.assign_industry',)}}"
          var assigner_list_url = "{{url_for('assigner.invest_list',)}}"
        </script>
        <script type="text/javascript" src="/static/javascripts/assigner.js"></script>


        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />


        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <script>
        $(function(){
          $('input[name="investDate"]').daterangepicker({
            autoUpdateInput: false,
            locale: {
              format: 'YYYY-MM-DD'
            }
          });

          $('input[name="investDate"]').on('cancel.daterangepicker', function(ev, picker) {
              $(this).val('');
          });
        });
        </script>

</head>
<body>
    <div id="container" class="box">
            <nav id="main" class="constrain clearfix">
                    <div class="menu-top-container">
                        <ul id="menu-top" class="menu">
                            <li class="menu-item" data-name="servinfo"><a href="/logout">项目/公司</a></li>
                            <li class="menu-item current" data-name="servinfo"><a>投融资事件</a></li>
                            <li class="menu-item" data-name="servinfo"><a href="/logout">投资机构</a></li>
                            <li class="menu-item" data-name="login"><a href="/ejs?__=login">登录</a></li>
                            <li class="menu-item" data-name="regist"><a href="/ejs?__=regist">注册</a></li>
                        </ul>
                    </div>
                </nav>
            <div id="content-wrapper" class="clearfix row auto">
                <div>
                    <div class="head_filter">
                        <label style="color: #00b8c0; font-size: 16px; margin-left: 25px;">投资日期：</label>
                    </div>
                    <div class="head_filter"><input name="investDate" style="width: 200px; z-index: 10000;" id="investDate" placeholder="" value=""></input>
                    </div>
                    <div style="width: 80%"></div>
                </div>
                </br>
                <p>
                    <hr style="height:10px;border:none;border-top:1px groove skyblue;" />
                </p>
                <div width="100%">
                        <div class="head_filter">
                            <label style="color: #00b8c0; font-size: 16px; margin-left: 25px;">关键词(公司/项目):</label>
                        </div>
                        <div class="head_filter"><input name="keyWords" style="width: 200px; z-index: 10000;" placeholder="请输入关键词" value="" id="keyWords"></input></div>
                    </div>
                    </br>
                    <p>
                        <hr style="height:10px;border:none;border-top:1px groove skyblue;" />
                    </p>
                <div width="100%">
                        <div class="head_filter">
                            <label style="color: #00b8c0; font-size: 16px; margin-left: 25px;">区域：</label>
                        </div>
                        <div class="head_filter"><span class="country filter_font" id="all">不限</span></div>
                        <div class="head_filter"><span class="country" id="gn">国内</span></div>
                        <div class="head_filter"><span class="country" id="gw">国外</span></div>
                    </div>
                    </br>
                    <p>
                        <hr style="height:10px;border:none;border-top:1px groove skyblue;" />
                    </p>
                <div width="100%">
                    <div class="head_filter">
                        <label style="color: #00b8c0; font-size: 16px; margin-left: 25px;">投资轮次：</label>
                    </div>
                    <div class="head_filter"><span class="round filter_font" id="all">不限</span></div>
                    <div class="head_filter"><span class="round" id="zhongzi">种子轮</span></div>
                    <div class="head_filter"><span class="round" id="tianshi">天使轮</span></div>
                    <div class="head_filter"><span class="round" id="pre_a">Pre-A轮</span></div>
                    <div class="head_filter"><span class="round" id="a">A轮</span></div>
                    <div class="head_filter"><span class="round" id="a_add">A+轮</span></div>
                    <div class="head_filter"><span class="round" id="pre_b">Pre-B轮</span></div>
                    <div class="head_filter"><span class="round" id="b">B轮</span></div>
                    <div class="head_filter"><span class="round" id="b_add">B+轮</span></div>
                    <div class="head_filter"><span class="round" id="c">C轮</span></div>
                    <div class="head_filter"><span class="round" id="d">D轮</span></div>
                    <div class="head_filter"><span class="round" id="other">其它</span></div>
                </div>
                </br>
                <p>
                    <hr style="height:10px;border:none;border-top:1px groove skyblue;" />
                </p>
                <div width="100%">
                    <div class="head_filter">
                        <label style="color: #00b8c0; font-size: 16px; margin-left: 25px;">所属行业：</label>
                    </div>
                    <div class="head_filter"><span class="industry filter_font" id="all">不限</span></div>
                    <div class="head_filter"><span class="industry" id="xfsj">消费升级</span></div>
                    <div class="head_filter"><span class="industry" id="xjs">新技术</span></div>
                    <div class="head_filter"><span class="industry" id="qyfw">企业服务</span></div>
                    <div class="head_filter"><span class="industry" id="whyl">文娱+移动2C</span></div>
                    <div class="head_filter"><span class="industry" id="jr">互联网金融</span></div>
                    <div class="head_filter"><span class="industry" id="yl">医疗</span></div>
                    <div class="head_filter"><span class="industry" id="jy">教育</span></div>
                    <div class="head_filter"><span class="industry" id="dcx">大出行</span></div>
                    <div class="head_filter"><span class="industry" id="other">其它</span></div>
                </div>
                </br>
                <p>
                    <hr style="height:10px;border:none;border-top:1px groove skyblue;" />
                <div width="100%">
                    <div class="head_filter">
                        <label style="color: #00b8c0; font-size: 16px; margin-left: 25px;">归类：</label>
                    </div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="xfsj">消费升级</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)"id="xjs">新技术</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="qyfw">企业服务</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="whyl">文娱+移动2C</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="jr">互联网金融</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="yl">医疗</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="jy">教育</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="dcx">大出行</button></div>
                    <div class="head_filter"><button onclick="assign_industry(this)" id="other">其它</button></div>
                </div>
                </br>
                <p>
                    <hr style="height:10px;border:none;border-top:10px groove skyblue;" />
                </p>
                <div id="table" >
                    <table id="invest" class="cell-border hover order-column" style="width:100%;" >
                        <thead>
                            <tr>
                                <th width="10%">项目名称</th>
                                <th width="5%">融资日期</th>
                                <th width="5%">融资轮次</th>
                                <th width="60%">项目简介</th>
                                <th width="10%">网站行业分类</th>
                                <th width="10%">行业分类</th>
                            </tr>
                        </thead>
                        <tbody class="clearfix row auto">
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
</body>
</html>